services:
  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgressql/data
    ports:
      - 5432:5432

volumes:
  db-data:
